### ISSUE TITLE
Crash for Unified Items

### ISSUE THREAD

**Issue by DatrixTHLK** [chazwarp923/Unified-Items#17]
Hello chazwarp923,

I like the concept of this mod, however, Minecraft just CTD'd with your mod being the culprit in the Crash Report. All I did was start up minecraft.

Minecraft 1.12.2
Forge: 14.23.0.2512
Unified Items: 1.12.2-1.7.2-206

Crash Report: https://gist.github.com/DatrixTHLK/3f6f38946ed6ff47475abd3e9ff13deb
FML Log: https://gist.github.com/DatrixTHLK/7ecaad14f97beb07c16e436c0fc9ff4e

**Comment by chazwarp923** [comment]
It quite clearly says in the crash report that this intended behavior. It only does it on first run, or if you ever delete the config.

**Comment by DatrixTHLK** [comment]
Thanks for the information. To be blunt, I never deleted the config in the first place. This is my first time back to Minecraft and 1.12. Which means there weren't any configs in the config file until I started up minecraft.

Intended behavior? I've never seen minecraft crash while creating a config file. I've seen them crash while having a config file that needed to removed in order to create a new config file with a new update for a mod. 

I'll check it out and see if it happens again after work.

**Comment by chazwarp923** [comment]
I purposely crash the game because on first launch i detect what other mods are installed in order to adjust generation rates. And because all of my blocks are added dynamically none of them exist on first launch since the mod doesn't know what to add yet. So in order to stop you from starting a world without and of my blocks i crash the game. Granted it's not the most elegant solution but its better than just putting text on the screen that says "Please restart your client before creating any worlds" because most people are just going to click continue and ignore it then complain when it doesn't work.

**Comment by DatrixTHLK** [comment]
Ah I see. That is one way to do it. Also, game works as intended just as you said before. Again, thanks for the information.
